export enum Permission {
  VIEW_OWN_ACCOUNT = 'VIEW_OWN_ACCOUNT',
  DEPOSIT = 'DEPOSIT',
  INVEST = 'INVEST',
  REQUEST_WITHDRAWAL = 'REQUEST_WITHDRAWAL',
  VIEW_ASSIGNED_TRADING_ACCOUNTS = 'VIEW_ASSIGNED_TRADING_ACCOUNTS',
  SUBMIT_TRADING_PERFORMANCE = 'SUBMIT_TRADING_PERFORMANCE',
  REVIEW_FINANCIAL_TRANSACTIONS = 'REVIEW_FINANCIAL_TRANSACTIONS',
  REVIEW_KYC = 'REVIEW_KYC',
  REVIEW_SUSPICIOUS_ACTIVITY = 'REVIEW_SUSPICIOUS_ACTIVITY',
  MANAGE_PLATFORM = 'MANAGE_PLATFORM',
  SYSTEM_CONFIG = 'SYSTEM_CONFIG',
}

const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  USER: [
    Permission.VIEW_OWN_ACCOUNT,
    Permission.DEPOSIT,
    Permission.INVEST,
    Permission.REQUEST_WITHDRAWAL,
  ],
  SUPPORT: [],
  FINANCE: [Permission.REVIEW_FINANCIAL_TRANSACTIONS],
  TRADER: [
    Permission.VIEW_ASSIGNED_TRADING_ACCOUNTS,
    Permission.SUBMIT_TRADING_PERFORMANCE,
  ],
  RISK_MANAGER: [Permission.REVIEW_SUSPICIOUS_ACTIVITY],
  COMPLIANCE: [Permission.REVIEW_KYC, Permission.REVIEW_SUSPICIOUS_ACTIVITY],
  ADMIN: [
    Permission.REVIEW_KYC,
    Permission.REVIEW_SUSPICIOUS_ACTIVITY,
    Permission.MANAGE_PLATFORM,
  ],
  SUPER_ADMIN: [
    Permission.REVIEW_KYC,
    Permission.REVIEW_SUSPICIOUS_ACTIVITY,
    Permission.MANAGE_PLATFORM,
    Permission.SYSTEM_CONFIG,
  ],
};

export function hasPermission(role: string, permission: Permission): boolean {
  return (ROLE_PERMISSIONS[role] ?? []).includes(permission);
}
