/**
 * Webhook verification and validation.
 * Verifies HMAC signatures and payload integrity.
 */

import crypto from 'crypto';

export interface WebhookPayload {
  event: string;
  transactionId: string;
  status: 'SUCCESS' | 'FAILED' | 'REFUNDED' | 'PENDING';
  amount?: string;
  currency?: string;
  timestamp: string;
  metadata?: Record<string, unknown>;
}

/**
 * Webhook signature verification configuration.
 * In production, store the webhook secret securely in environment or Key Vault.
 */
export class WebhookVerifier {
  private webhookSecret: string;

  constructor(webhookSecret: string = process.env.WEBHOOK_SECRET || 'demo-webhook-secret-key') {
    this.webhookSecret = webhookSecret;
  }

  /**
   * Verify webhook signature using HMAC-SHA256.
   * Prevents spoofed webhooks from unauthorized sources.
   *
   * @param payload - Raw request body as string
   * @param signature - X-Webhook-Signature header value
   * @returns true if signature is valid
   */
  verifySignature(payload: string, signature: string): boolean {
    const computed = crypto
      .createHmac('sha256', this.webhookSecret)
      .update(payload)
      .digest('hex');

    // If lengths differ, signature is invalid (prevent length mismatch error)
    if (computed.length !== signature.length) {
      return false;
    }

    // Constant-time comparison to prevent timing attacks
    try {
      return crypto.timingSafeEqual(Buffer.from(computed), Buffer.from(signature));
    } catch {
      return false;
    }
  }

  /**
   * Validate webhook payload structure and required fields.
   *
   * @param payload - Parsed webhook payload
   * @returns { valid: boolean; reason?: string }
   */
  validatePayload(payload: unknown): { valid: boolean; reason?: string } {
    if (typeof payload !== 'object' || payload === null) {
      return { valid: false, reason: 'Payload must be a JSON object.' };
    }

    const p = payload as Record<string, unknown>;

    if (!p.event || typeof p.event !== 'string') {
      return { valid: false, reason: 'Event type is required.' };
    }

    if (!p.transactionId || typeof p.transactionId !== 'string') {
      return { valid: false, reason: 'Transaction ID is required.' };
    }

    if (!p.status || typeof p.status !== 'string') {
      return { valid: false, reason: 'Status is required.' };
    }

    if (!['SUCCESS', 'FAILED', 'REFUNDED', 'PENDING'].includes(p.status as string)) {
      return { valid: false, reason: 'Invalid status value.' };
    }

    if (!p.timestamp || typeof p.timestamp !== 'string') {
      return { valid: false, reason: 'Timestamp is required.' };
    }

    // Validate timestamp is recent (within 5 minutes)
    const webhookTime = new Date(p.timestamp as string).getTime();
    const now = Date.now();
    const fiveMinutesMs = 5 * 60 * 1000;

    if (Math.abs(now - webhookTime) > fiveMinutesMs) {
      return { valid: false, reason: 'Webhook timestamp is too old or in the future.' };
    }

    return { valid: true };
  }

  /**
   * Parse and validate webhook payload.
   *
   * @param rawPayload - Raw request body
   * @param signature - X-Webhook-Signature header
   * @returns Parsed and validated webhook payload
   * @throws Error if signature verification or validation fails
   */
  parseAndVerify(rawPayload: string, signature: string): WebhookPayload {
    // Verify signature
    if (!this.verifySignature(rawPayload, signature)) {
      throw new Error('Webhook signature verification failed.');
    }

    // Parse JSON
    let payload: unknown;
    try {
      payload = JSON.parse(rawPayload);
    } catch (error) {
      throw new Error('Invalid JSON in webhook payload.');
    }

    // Validate structure
    const validation = this.validatePayload(payload);
    if (!validation.valid) {
      throw new Error(validation.reason ?? 'Webhook payload validation failed.');
    }

    return payload as WebhookPayload;
  }
}

/**
 * Generate test webhook signature for development/testing.
 * In production, this would be generated by the payment provider.
 *
 * @param payload - Webhook payload
 * @param secret - Webhook secret
 * @returns HMAC-SHA256 signature
 */
export function generateTestWebhookSignature(payload: Record<string, unknown>, secret: string): string {
  const rawPayload = JSON.stringify(payload);
  return crypto
    .createHmac('sha256', secret)
    .update(rawPayload)
    .digest('hex');
}
